/*----------------------------------------------------------------------------*/
/* Copyright (c) FIRST 2008-2016. All Rights Reserved.                        */
/* Open Source Software - may be modified and shared by FRC teams. The code   */
/* must be accompanied by the FIRST BSD license file in the root directory of */
/* the project.                                                               */
/*----------------------------------------------------------------------------*/

package edu.wpi.first.wpilibj;

import edu.wpi.first.wpilibj.communication.FRCNetworkCommunicationsLibrary.tResourceType;
import edu.wpi.first.wpilibj.communication.UsageReporting;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.livewindow.LiveWindowSendable;
import edu.wpi.first.wpilibj.tables.ITable;

/**
 * Ultrasonic rangefinder class. The Ultrasonic rangefinder measures absolute distance based on the
 * round-trip time of a ping generated by the controller. These sensors use two transducers, a
 * speaker and a microphone both tuned to the ultrasonic range. A common ultrasonic sensor, the
 * Daventech SRF04 requires a short pulse to be generated on a digital channel. This causes the
 * chirp to be emmitted. A second line becomes high as the ping is transmitted and goes low when the
 * echo is received. The time that the line is high determines the round trip distance (time of
 * flight).
 */
public class Ultrasonic extends SensorBase implements PIDSource, LiveWindowSendable {

  /**
   * The units to return when PIDGet is called.
   */
  public enum Unit {
    /**
     * Use inches for PIDGet.
     */
    kInches,
    /**
     * Use millimeters for PIDGet.
     */
    kMillimeters
  }

  private static final double kPingTime = 10 * 1e-6; // /< Time (sec) for the
  // ping trigger pulse.
  private static final int kPriority = 90; // /< Priority that the ultrasonic
  // round robin task runs.
  private static final double kMaxUltrasonicTime = 0.1; // /< Max time (ms)
  // between readings.
  private static final double kSpeedOfSoundInchesPerSec = 1130.0 * 12.0;
  private static Ultrasonic firstSensor = null; // head of the ultrasonic
  // sensor list
  private static boolean automaticEnabled = false; // automatic round robin
  // mode
  private DigitalInput echoChannel;
  private DigitalOutput pingChannel = null;
  private boolean allocatedChannels;
  private boolean enabled = false;
  private Counter counter = null;
  private Ultrasonic nextSensor = null;
  private static Thread task = null; // task doing the round-robin automatic
  // sensing
  private Unit units;
  private static int instances = 0;
  protected PIDSourceType pidSource = PIDSourceType.kDisplacement;

  /**
   * Background task that goes through the list of ultrasonic sensors and pings each one in turn.
   * The counter is configured to read the timing of the returned echo pulse.
   *
   * <p><b>DANGER WILL ROBINSON, DANGER WILL ROBINSON:</b> This code runs as a task and assumes that
   * none of the ultrasonic sensors will change while it's running. If one does, then this will
   * certainly break. Make sure to disable automatic mode before changing anything with the
   * sensors!!
   */
  private class UltrasonicChecker extends Thread {

    public synchronized void run() {
      Ultrasonic ultrasonic = null;
      while (automaticEnabled) {
        if (ultrasonic == null) {
          ultrasonic = firstSensor;
        }
        if (ultrasonic == null) {
          return;
        }
        if (ultrasonic.isEnabled()) {
          ultrasonic.pingChannel.pulse(pingChannel.m_channel, (float) kPingTime); // do
          // the
          // ping
        }
        ultrasonic = ultrasonic.nextSensor;
        Timer.delay(.1); // wait for ping to return
      }
    }
  }

  /**
   * Initialize the Ultrasonic Sensor. This is the common code that initializes the ultrasonic
   * sensor given that there are two digital I/O channels allocated. If the system was running in
   * automatic mode (round robin) when the new sensor is added, it is stopped, the sensor is added,
   * then automatic mode is restored.
   */
  private synchronized void initialize() {
    if (task == null) {
      task = new UltrasonicChecker();
    }
    final boolean originalMode = automaticEnabled;
    setAutomaticMode(false); // kill task when adding a new sensor
    nextSensor = firstSensor;
    firstSensor = this;

    counter = new Counter(echoChannel); // set up counter for this
    // sensor
    counter.setMaxPeriod(1.0);
    counter.setSemiPeriodMode(true);
    counter.reset();
    enabled = true; // make it available for round robin scheduling
    setAutomaticMode(originalMode);

    instances++;
    UsageReporting.report(tResourceType.kResourceType_Ultrasonic, instances);
    LiveWindow.addSensor("Ultrasonic", echoChannel.getChannel(), this);
  }

  /**
   * Create an instance of the Ultrasonic Sensor. This is designed to supchannel the Daventech SRF04
   * and Vex ultrasonic sensors.
   *
   * @param pingChannel The digital output channel that sends the pulse to initiate the sensor
   *                    sending the ping.
   * @param echoChannel The digital input channel that receives the echo. The length of time that
   *                    the echo is high represents the round trip time of the ping, and the
   *                    distance.
   * @param units       The units returned in either kInches or kMilliMeters
   */
  public Ultrasonic(final int pingChannel, final int echoChannel, Unit units) {
    this.pingChannel = new DigitalOutput(pingChannel);
    this.echoChannel = new DigitalInput(echoChannel);
    allocatedChannels = true;
    this.units = units;
    initialize();
  }

  /**
   * Create an instance of the Ultrasonic Sensor. This is designed to supchannel the Daventech SRF04
   * and Vex ultrasonic sensors. Default unit is inches.
   *
   * @param pingChannel The digital output channel that sends the pulse to initiate the sensor
   *                    sending the ping.
   * @param echoChannel The digital input channel that receives the echo. The length of time that
   *                    the echo is high represents the round trip time of the ping, and the
   *                    distance.
   */
  public Ultrasonic(final int pingChannel, final int echoChannel) {
    this(pingChannel, echoChannel, Unit.kInches);
  }

  /**
   * Create an instance of an Ultrasonic Sensor from a DigitalInput for the echo channel and a
   * DigitalOutput for the ping channel.
   *
   * @param pingChannel The digital output object that starts the sensor doing a ping. Requires a
   *                    10uS pulse to start.
   * @param echoChannel The digital input object that times the return pulse to determine the
   *                    range.
   * @param units       The units returned in either kInches or kMilliMeters
   */
  public Ultrasonic(DigitalOutput pingChannel, DigitalInput echoChannel, Unit units) {
    if (pingChannel == null || echoChannel == null) {
      throw new NullPointerException("Null Channel Provided");
    }
    allocatedChannels = false;
    this.pingChannel = pingChannel;
    this.echoChannel = echoChannel;
    this.units = units;
    initialize();
  }

  /**
   * Create an instance of an Ultrasonic Sensor from a DigitalInput for the echo channel and a
   * DigitalOutput for the ping channel. Default unit is inches.
   *
   * @param pingChannel The digital output object that starts the sensor doing a ping. Requires a
   *                    10uS pulse to start.
   * @param echoChannel The digital input object that times the return pulse to determine the
   *                    range.
   */
  public Ultrasonic(DigitalOutput pingChannel, DigitalInput echoChannel) {
    this(pingChannel, echoChannel, Unit.kInches);
  }

  /**
   * Destructor for the ultrasonic sensor. Delete the instance of the ultrasonic sensor by freeing
   * the allocated digital channels. If the system was in automatic mode (round robin), then it is
   * stopped, then started again after this sensor is removed (provided this wasn't the last
   * sensor).
   */
  public synchronized void free() {
    final boolean wasAutomaticMode = automaticEnabled;
    setAutomaticMode(false);
    if (allocatedChannels) {
      if (pingChannel != null) {
        pingChannel.free();
      }
      if (echoChannel != null) {
        echoChannel.free();
      }
    }

    if (counter != null) {
      counter.free();
      counter = null;
    }

    pingChannel = null;
    echoChannel = null;

    if (this == firstSensor) {
      firstSensor = nextSensor;
      if (firstSensor == null) {
        setAutomaticMode(false);
      }
    } else {
      for (Ultrasonic s = firstSensor; s != null; s = s.nextSensor) {
        if (this == s.nextSensor) {
          s.nextSensor = s.nextSensor.nextSensor;
          break;
        }
      }
    }
    if (firstSensor != null && wasAutomaticMode) {
      setAutomaticMode(true);
    }
  }

  /**
   * Turn Automatic mode on/off. When in Automatic mode, all sensors will fire in round robin,
   * waiting a set time between each sensor.
   *
   * @param enabling Set to true if round robin scheduling should start for all the ultrasonic
   *                 sensors. This scheduling method assures that the sensors are non-interfering
   *                 because no two sensors fire at the same time. If another scheduling algorithm
   *                 is preffered, it can be implemented by pinging the sensors manually and waiting
   *                 for the results to come back.
   */
  public void setAutomaticMode(boolean enabling) {
    if (enabling == automaticEnabled) {
      return; // ignore the case of no change
    }
    automaticEnabled = enabling;

    if (enabling) {
      /* Clear all the counters so no data is valid. No synchronization is
       * needed because the background task is stopped.
       */
      for (Ultrasonic u = firstSensor; u != null; u = u.nextSensor) {
        u.counter.reset();
      }

      // Start round robin task
      task.start();
    } else {
      // Wait for background task to stop running
      try {
        task.join();
      } catch (InterruptedException ex) {
        Thread.currentThread().interrupt();
        ex.printStackTrace();
      }

      /* Clear all the counters (data now invalid) since automatic mode is
       * disabled. No synchronization is needed because the background task is
       * stopped.
       */
      for (Ultrasonic u = firstSensor; u != null; u = u.nextSensor) {
        u.counter.reset();
      }
    }
  }

  /**
   * Single ping to ultrasonic sensor. Send out a single ping to the ultrasonic sensor. This only
   * works if automatic (round robin) mode is disabled. A single ping is sent out, and the counter
   * should count the semi-period when it comes in. The counter is reset to make the current value
   * invalid.
   */
  public void ping() {
    setAutomaticMode(false); // turn off automatic round robin if pinging
    // single sensor
    counter.reset(); // reset the counter to zero (invalid data now)
    pingChannel.pulse(pingChannel.m_channel, (float) kPingTime); // do
    // the
    // ping
    // to
    // start
    // getting
    // a
    // single
    // range
  }

  /**
   * Check if there is a valid range measurement. The ranges are accumulated in a counter that will
   * increment on each edge of the echo (return) signal. If the count is not at least 2, then the
   * range has not yet been measured, and is invalid.
   *
   * @return true if the range is valid
   */
  public boolean isRangeValid() {
    return counter.get() > 1;
  }

  /**
   * Get the range in inches from the ultrasonic sensor. If there is no valid value yet, i.e. at
   * least one measurement hasn't completed, then return 0.
   *
   * @return double Range in inches of the target returned from the ultrasonic sensor.
   */
  public double getRangeInches() {
    if (isRangeValid()) {
      return counter.getPeriod() * kSpeedOfSoundInchesPerSec / 2.0;
    } else {
      return 0;
    }
  }

  /**
   * Get the range in millimeters from the ultrasonic sensor. If there is no valid value yet, i.e.
   * at least one measurement hasn't completed, then return 0.
   *
   * @return double Range in millimeters of the target returned by the ultrasonic sensor.
   */
  public double getRangeMM() {
    return getRangeInches() * 25.4;
  }

  @Override
  public void setPIDSourceType(PIDSourceType pidSource) {
    if (!pidSource.equals(PIDSourceType.kDisplacement)) {
      throw new IllegalArgumentException("Only displacement PID is allowed for ultrasonics.");
    }
    this.pidSource = pidSource;
  }

  @Override
  public PIDSourceType getPIDSourceType() {
    return pidSource;
  }

  /**
   * Get the range in the current DistanceUnit for the PIDSource base object.
   *
   * @return The range in DistanceUnit
   */
  @Override
  public double pidGet() {
    switch (units) {
      case kInches:
        return getRangeInches();
      case kMillimeters:
        return getRangeMM();
      default:
        return 0.0;
    }
  }

  /**
   * Set the current DistanceUnit that should be used for the PIDSource base object.
   *
   * @param units The DistanceUnit that should be used.
   */
  public void setDistanceUnits(Unit units) {
    this.units = units;
  }

  /**
   * Get the current DistanceUnit that is used for the PIDSource base object.
   *
   * @return The type of DistanceUnit that is being used.
   */
  public Unit getDistanceUnits() {
    return units;
  }

  /**
   * Is the ultrasonic enabled.
   *
   * @return true if the ultrasonic is enabled
   */
  public boolean isEnabled() {
    return enabled;
  }

  /**
   * Set if the ultrasonic is enabled.
   *
   * @param enable set to true to enable the ultrasonic
   */
  public void setEnabled(boolean enable) {
    this.enabled = enable;
  }

  /*
   * Live Window code, only does anything if live window is activated.
   */
  @Override
  public String getSmartDashboardType() {
    return "Ultrasonic";
  }

  private ITable table;

  @Override
  public void initTable(ITable subtable) {
    table = subtable;
    updateTable();
  }

  @Override
  public ITable getTable() {
    return table;
  }

  @Override
  public void updateTable() {
    if (table != null) {
      table.putNumber("Value", getRangeInches());
    }
  }

  @Override
  public void startLiveWindowMode() {
  }

  @Override
  public void stopLiveWindowMode() {
  }
}
